// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj10Jrq-gwsCIrC4hjLwzLT8Lz560qTUg',
    appId: '1:893991898029:web:07280ed2244e741c8daf24',
    messagingSenderId: '893991898029',
    projectId: 'developistore',
    authDomain: 'developistore.firebaseapp.com',
    databaseURL: 'https://developistore.firebaseio.com',
    storageBucket: 'developistore.appspot.com',
    measurementId: 'G-J5DMVN9NVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_4_qY_mNZDu9L-jkKn6FPJvfCsP3WvtQ',
    appId: '1:893991898029:android:2d3a188f1c9ba2ed8daf24',
    messagingSenderId: '893991898029',
    projectId: 'developistore',
    databaseURL: 'https://developistore.firebaseio.com',
    storageBucket: 'developistore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD776ibAkhS8WWCZhtAmnvGwtZNqD6ZPwk',
    appId: '1:893991898029:ios:94f8047923097ed98daf24',
    messagingSenderId: '893991898029',
    projectId: 'developistore',
    databaseURL: 'https://developistore.firebaseio.com',
    storageBucket: 'developistore.appspot.com',
    androidClientId: '893991898029-3h6hg924vr7petioeuu67hiareh44saf.apps.googleusercontent.com',
    iosClientId: '893991898029-5kb230smqqomos239srs1l07s7elch7s.apps.googleusercontent.com',
    iosBundleId: 'com.developitech.fastfill',
  );
}
